spring:
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:src/main/resources/static
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.20.128.2:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ranyewumysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false
logging:
  level:
    root: info
    com.example: debug
  file:
    name: log/blog-dev.log
server:
  port: 8081